### PR TITLE
Peers blacklisting

### LINKED ISSUE #177: Node blacklisting
Implement nodes blacklisting on incorrect behaviour

### PR DESCRIPTION
**Pull request by oskin1**
Close #177 

This PR implements the following blacklisting algorithm:
Penalties are divided into 4 categories:

1. NonDeliveryPenalty - applied when a peer did not deliver requested modifier in time
2. MisbehaviorPenalty - applied when some modifier delivered by peer appeared to be invalid
3. SpamPenalty - applied when a peer delivered non-requested modifier
4. PermanentPenalty - applied to peers conforming to a different protocol (failed to parse message from a peer)

- Once some penalty is applied a penalized peer accumulates `penaltyScore` (varies depending on penalty type: `NonDeliveryPenalty` - `2`; `MisbehaviorPenalty` - `10`; `SpamPenalty ` - `25`; `PermanentPenalty` - `∞`; )
- Penalties of type 1, 2, 3 are not applied repeatedly within a safe interval (defined by `scorex.network.penaltySafeInterval` - default: 5m)
- Once some peer accumulates critical penalty score (defined by `scorex.network.penaltyScoreThreshold` - default: 100) it gets banned for some time (defined by `scorex.network.temporalBanDuration` - default: 60m)
- The PermanentPenalty is applied immediately and leads to a permanent ban of a peer

### CODE REVIEW

File: src/main/scala/scorex/core/network/peer/PenaltyType.scala [hunk 1]
```diff
@@ -0,0 +1,27 @@
...
+  case object MisbehaviorPenalty extends PenaltyType {
+    override val penaltyScore: Int = 10
+  }
+
+  case object SpamPenalty extends PenaltyType {
+    override val penaltyScore: Int = 25
+  }
+
+  case object PermanentPenalty extends PenaltyType {
+    override val penaltyScore: Int = 1000000000
```
Comment (catena2w) [inline src/main/scala/scorex/core/network/peer/PenaltyType.scala]:
```suggestion
    override val penaltyScore: Int = Int.MaxValue
```

File: src/main/scala/scorex/core/network/peer/PenaltyType.scala [hunk 2]
```diff
@@ -0,0 +1,27 @@
+package scorex.core.network.peer
+
+sealed trait PenaltyType {
```
Comment (catena2w) [inline src/main/scala/scorex/core/network/peer/PenaltyType.scala]: Please add class and it's fields description

File: src/main/scala/scorex/core/network/peer/PenaltyType.scala (hunk 1 above)
Comment (oskin1) [reply src/main/scala/scorex/core/network/peer/PenaltyType.scala]: This would cause integer overflow when we sum it up with another score. `1000000000` is enough.

File: src/main/scala/scorex/core/network/NodeViewSynchronizer.scala [hunk 3]
```diff
@@ -539,7 +530,7 @@ object NodeViewSynchronizer {
     //hierarchy of events regarding modifiers application outcome
     trait ModificationOutcome extends NodeViewHolderEvent
 
-    case class FailedTransaction[TX <: Transaction](transaction: TX, error: Throwable) extends ModificationOutcome
+    case class FailedTransaction(transactionId: ModifierId, error: Throwable, immediateFailure: Boolean) extends ModificationOutcome
```
[the remark this answers is not in the document]
Comment (oskin1) [reply src/main/scala/scorex/core/network/NodeViewSynchronizer.scala]: `immediateFailure` is a flag indicating whether a transaction was invalid by the moment it was received.

File: src/main/scala/scorex/core/network/DeliveryTracker.scala [hunk 4]
```diff
@@ -102,98 +84,107 @@ class DeliveryTracker(system: ActorSystem,
...
+    * Set status of modifier with id `id` to `Requested`
     */
-  def onReceive(mid: ModifierId): Unit = tryWithLogging {
-    updateStatus(mid, Received)
+  def setRequested(id: ModifierId,
+                   typeId: ModifierTypeId,
+                   supplierOpt: Option[ConnectedPeer],
+                   checksDone: Int = 0)
+                  (implicit ec: ExecutionContext): Unit = tryWithLogging {
+    assert(isCorrectTransition(status(id), Requested), s"Illegal status transition: ${status(id)} -> Requested")
```
[the remark this answers is not in the document]
Comment (oskin1) [reply src/main/scala/scorex/core/network/DeliveryTracker.scala]: It is not a part of normal flow. If incorrect transition happens we should know about it immediately in order to fix the logic.

File: src/main/scala/scorex/core/network/peer/PenaltyType.scala (hunk 2 above)
Comment (oskin1) [reply src/main/scala/scorex/core/network/peer/PenaltyType.scala]: Done

File: src/main/scala/scorex/core/network/NetworkController.scala [hunk 5]
```diff
@@ -405,6 +421,24 @@ class NetworkController(settings: NetworkSettings,
       }
     }
   }
+
+  /**
+    * Close connection and ban peer.
+    */
+  private def blacklist(peerAddress: InetSocketAddress): Unit =
```
[the remark this answers is not in the document]
Comment (oskin1) [reply src/main/scala/scorex/core/network/NetworkController.scala]: Done

**Comment by kushti** [comment]
@oskin1 accepted, but please get tryWithLogging back
