### PR TITLE
#296: Peer discovery fix

### LINKED ISSUE #296: Peer discovery
We wrote a test for peers discovery (issue https://github.com/ergoplatform/ergo/issues/253, PR https://github.com/ergoplatform/ergo/pull/371), and looks like peer discovery does not work - if there is a connection betweern nodes 1-2 and 1-3, connection between nodes 2-3 is not created.
Can be reproduced in Scorex by running 3 nodes of `examples/src/main/scala/examples/hybrid/HybridApp.scala` with configs: 
```
examples/src/main/resources/settings.conf
examples/src/main/resources/settings2.conf
examples/src/main/resources/settings3.conf
```

### PR DESCRIPTION
**Pull request by VictorMikheev**
Fix #296 
- Use automatically assigned local port (not from declaredAdress) for outgoing connection to peer 
- Use DeclaredAddress as a key for peer database instead of peer connection local socket address
- Added trace logs for peer database

### CODE REVIEW

File: src/main/scala/scorex/core/network/peer/PeerDatabaseImpl.scala [hunk 1]
```diff
@@ -27,6 +29,7 @@ class PeerDatabaseImpl(filename: Option[String]) extends PeerDatabase {
   }
 
   override def blacklistPeer(address: InetSocketAddress, time: NetworkTime.Time): Unit = {
+    log.trace(s"Black list peer: ${address.toString}")
```
Comment (catena2w) [inline src/main/scala/scorex/core/network/peer/PeerDatabaseImpl.scala]: Log level should be higher here, info/warn

File: src/test/scala/scorex/core/network/peer/PeerManagerSpec.scala [hunk 2]
```diff
@@ -83,8 +83,8 @@ class PeerManagerSpec extends FlatSpec with Matchers with ObjectGenerators {
     val data1 = pr1.expectMsgClass(classOf[Data])
     data1.keySet should contain(pa1)
 
-    val h2 = Handshake("test", Version(1: Byte, 2: Byte, 3: Byte), "1", Some(pa2), feats, System.currentTimeMillis())
-    //connected peer became non-public cause declared address != peerAddress
+    val h2 = Handshake("test", Version(1: Byte, 2: Byte, 3: Byte), "1", None, feats, System.currentTimeMillis())
```
Comment (catena2w) [inline src/test/scala/scorex/core/network/peer/PeerManagerSpec.scala]: Does declared address feature works now?

Comment (VictorMikheev) [reply src/test/scala/scorex/core/network/peer/PeerManagerSpec.scala]: I think it works

Comment (VictorMikheev) [reply src/test/scala/scorex/core/network/peer/PeerManagerSpec.scala]: I traied to run HybridApp with changes in this PR.

Nodes with default settings not discover peers for the following reasons: 
1) setting declaredAddress is not defined
2) upnp is disabled

When declaredAdress is definded peer discovery is work fine.

**Comment by catena2w** [comment]
Let's try to use this part more user-friendly - without special config section nodes should understand, whether they are public or not, and should connect to all nodes they can (including local one)

File: src/main/scala/scorex/core/api/http/PeersApiRoute.scala [hunk 3]
```diff
@@ -13,11 +13,13 @@ import scorex.core.network.NetworkController.ReceivableMessages.ConnectTo
 import scorex.core.network.peer.PeerInfo
 import scorex.core.network.peer.PeerManager.ReceivableMessages.{GetAllPeers, GetBlacklistedPeers, GetConnectedPeers}
 import scorex.core.settings.RESTApiSettings
+import scorex.core.utils.NetworkTimeProvider
 
 import scala.concurrent.ExecutionContext
 
 case class PeersApiRoute(peerManager: ActorRef,
                          networkController: ActorRef,
+                         timeProvider: NetworkTimeProvider,
```
Comment (catena2w) [inline src/main/scala/scorex/core/api/http/PeersApiRoute.scala]: Let's use `timeProvider` at `val now = System.currentTimeMillis()`

File: src/main/scala/scorex/core/api/http/PeersApiRoute.scala [hunk 4]
```diff
@@ -55,7 +57,8 @@ case class PeersApiRoute(peerManager: ActorRef,
       case Some(addressAndPort) =>
         val host = InetAddress.getByName(addressAndPort.group(1))
         val port = addressAndPort.group(2).toInt
-        networkController ! ConnectTo(new InetSocketAddress(host, port))
+        val peerInfo = PeerInfo(timeProvider.time(), new InetSocketAddress(host, port), None, None, Seq())
```
Comment (catena2w) [inline src/main/scala/scorex/core/api/http/PeersApiRoute.scala]: Let's allow to provide `nodeName` (not sure about connectionType) via API instead of setting it always to `None`.

File: src/main/scala/scorex/core/network/NetworkController.scala [hunk 5]
```diff
@@ -38,7 +41,10 @@ class NetworkController(settings: NetworkSettings,
 
   private implicit val system: ActorSystem = context.system
 
-  private val featureSerializers: PeerFeature.Serializers = features.map(f => f.featureId -> f.serializer).toMap
+  val a  = LocalAddressPeerFeature.featureId -> LocalAddressPeerFeatureSerializer
```
Comment (catena2w) [inline src/main/scala/scorex/core/network/NetworkController.scala]: `a` is a very bad name. Also it should by private as soon as other members are also private

File: src/main/scala/scorex/core/network/NetworkController.scala [hunk 6]
```diff
@@ -70,24 +74,41 @@ class NetworkController(settings: NetworkSettings,
...
       if (settings.upnpEnabled) {
         upnp.externalAddress.map(a => new InetSocketAddress(a, settings.bindAddress.getPort))
       } else None
+    } orElse {
+      getPublicAddress
     }
   }
 
-  log.info(s"Declared address: $externalSocketAddress")
+  private def getPublicAddress = {
```
Comment (catena2w) [inline src/main/scala/scorex/core/network/NetworkController.scala]: please add comments with method description

Comment (catena2w) [reply src/main/scala/scorex/core/network/NetworkController.scala]: Also it may be `val` instead of `def`.

File: src/main/scala/scorex/core/network/NetworkController.scala [hunk 7]
```diff
@@ -70,24 +74,41 @@ class NetworkController(settings: NetworkSettings,
...
+      val addr = allAddrs.filterNot(a => a.isSiteLocalAddress || a.isLoopbackAddress).headOption
+      addr.map(a => new InetSocketAddress(a, bindAddress.getPort))
+    } else if (!bindAddress.getAddress.isSiteLocalAddress) {
+      Some(bindAddress)
+    } else {
+      None
+    }
+  }
 
+  log.info(s"Declared address: $externalSocketAddress")
```
Comment (catena2w) [inline src/main/scala/scorex/core/network/NetworkController.scala]: as far as we touch `externalSocketAddress` here, it should not be lazy I think

File: src/main/scala/scorex/core/network/NetworkController.scala [hunk 8]
```diff
@@ -191,14 +227,29 @@ class NetworkController(settings: NetworkSettings,
     case nonsense: Any =>
       log.warn(s"NetworkController: got something strange $nonsense")
   }
+
+  private def getPeerAddress(peer: PeerInfo): InetSocketAddress = {
```
Comment (catena2w) [inline src/main/scala/scorex/core/network/NetworkController.scala]: please provide method description
